intercom_survey_responses:
  outputs:
    dev:
      dataset: intercom_survey_responses_dev
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: ../google-service-account-intercom-survey-responses-runtime.json
      location: EU
      method: service-account
      priority: interactive
      project: alva-analytics
      threads: 1
      type: bigquery
    prod:
      dataset: intercom_survey_responses
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: ../google-service-account-intercom-survey-responses-runtime.json
      location: EU
      method: service-account
      priority: interactive
      project: alva-analytics
      threads: 1
      type: bigquery
  target: dev
