version: 2

models:
  - name: dim_dates
    description: "Dates used to aggregate and analyze data"
    columns:

      - name: date_day
        description: "Date of the day"
        data_type: date
      
      - name: day_of_week
        description: "Day of week"
        data_type: integer

      - name: day_of_month
        description: "Day of month"
        data_type: integer

      - name: day_of_year
        description: "Day of year"
        data_type: integer

      - name: week_of_year
        description: "Week of year"
        data_type: integer

      - name: month_of_year
        description: "Month of year"
        data_type: integer

      - name: month_name
        description: "Name of the month"
        data_type: string

      - name: quarter_of_year
        description: "Quarter of year"
        data_type: integer

      - name: year_number
        description: "Year"
        data_type: integer


  - name: csat_response
    description: "Customer satisfaction survey responses"
    config:
      contract:
        enforced: true
    columns:

      - name: survey_content_id
        description: "The survey content identifier"
        data_type: integer
      - name: survey_content_title
        description: "Title of the survey"
        data_type: string
      - name: respondent_email
        description: "Email of the survey respondent"
        data_type: string
      - name: organization_id
        description: "Organization identifier"
        data_type: integer
      - name: organization_name
        description: "Name of the organization"
        data_type: string
      - name: question_id
        description: "Question identifier"
        data_type: integer
      - name: answered_at
        description: "Timestamp when the response was submitted"
        data_type: timestamp
      - name: answered_at_date
        description: "Date when the response was submitted"
        data_type: date
      - name: response
        description: "Numeric response value (1-5)"
        data_type: integer
      - name: category
        description: "Categorized response (positive/neutral/negative)"
        data_type: string

  - name: nps_response
    description: "Net Promoter Score survey responses"
    config:
      contract:
        enforced: true
    columns:

      - name: survey_content_id
        description: "The survey content identifier"
        data_type: integer
      - name: survey_content_title
        description: "Title of the survey"
        data_type: string
      - name: respondent_email
        description: "Email of the survey respondent"
        data_type: string
      - name: organization_id
        description: "Organization identifier"
        data_type: integer
      - name: organization_name
        description: "Name of the organization"
        data_type: string
      - name: question_id
        description: "Question identifier"
        data_type: integer
      - name: answered_at
        description: "Timestamp when the response was submitted"
        data_type: timestamp
      - name: answered_at_date
        description: "Date when the response was submitted"
        data_type: date
      - name: response
        description: "Numeric response value (0-10)"
        data_type: integer
      - name: category
        description: "NPS category (promoter/passive/detractor)"
        data_type: string