version: 2

models:
  - name: csat_score
    description: "CSAT score calculated monthly as (number of 4+ ratings) / (total responses)"
    config:
      contract:
        enforced: true
    columns:

      - name: month_start_date
        description: "Month number (1-12) of the CSAT measurement"
        data_type: "date"
        constraints:
          - type: not_null

      - name: csat_score
        description: "Monthly CSAT score calculated as (ratings >= 4) / (total responses), rounded to 2 decimal places"
        data_type: "float"
        constraints:
          - type: not_null

  - name: nps_score
    description: "Net Promoter Score (NPS) calculated as ((promoters - detractors) / total responses) * 100"
    config:
      contract:
        enforced: true
    columns:
      - name: month_start_date
        description: "Month number (1-12) of the CSAT measurement"
        data_type: "date"
        constraints:
          - type: not_null

      - name: nps_score
        description: "Net Promoter Score calculated as ((promoters - detractors) / total responses) * 100, rounded to nearest integer"
        data_type: "float"
        constraints:
          - type: not_null