version: 1

models:

  - name: csat_score
    description: "CSAT score calculated monthly as (number of 4+ ratings) / (total responses)"
    config:
      contract:
        enforced: true
    columns:

      - name: year_number
        description: "Year of the CSAT measurement"
        data_type: "integer"
        constraints:
          - type: not_null

      - name: month_of_year
        description: "Month number (1-12) of the CSAT measurement"
        data_type: "integer"
        constraints:
          - type: not_null

      - name: month_name
        description: "Month name of the CSAT measurement"
        data_type: "string"
        constraints:
          - type: not_null

      - name: csat_score
        description: "Monthly CSAT score calculated as (ratings >= 4) / (total responses), rounded to 2 decimal places"
        data_type: "float"
        constraints:
          - type: not_null

  - name: nps_score
    description: "Net Promoter Score (NPS) calculated as ((promoters - detractors) / total responses) * 100"
    config:
      contract:
        enforced: true
    columns:
      - name: response_count
        description: "Total number of NPS responses"
        data_type: "integer"
        constraints:
          - type: not_null

      - name: n_promoters
        description: "Number of promoter responses (customers who gave a high rating)"
        data_type: "integer"
        constraints:
          - type: not_null

      - name: n_detractors
        description: "Number of detractor responses (customers who gave a low rating)"
        data_type: "integer"
        constraints:
          - type: not_null

      - name: nps_score
        description: "Net Promoter Score calculated as ((promoters - detractors) / total responses) * 100, rounded to nearest integer"
        data_type: "float"
        constraints:
          - type: not_null